# Generated by Django 5.2.4 on 2025-08-09 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrudModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=200)),
                ("LastName", models.CharField(max_length=200)),
                ("Address", models.CharField(max_length=200)),
                ("EmailId", models.EmailField(max_length=100, unique=True)),
                (
                    "PhoneNumber",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$", "Enter a valid 10-digit number"
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
