# Generated by Django 5.2.4 on 2025-08-09 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crudmodels",
            name="EmailId",
            field=models.EmailField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w\\.-]+@(gmail|yahoo|outlook)+\\.[a-z]{2,}$"
                    )
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="crudmodels",
            unique_together={("FirstName", "LastName")},
        ),
    ]
