# Generated by Django 5.2.4 on 2025-08-09 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0002_alter_crudmodels_emailid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crudmodels",
            options={"verbose_name": "Contact", "verbose_name_plural": "Contacts"},
        ),
        migrations.AlterField(
            model_name="crudmodels",
            name="EmailId",
            field=models.EmailField(
                error_messages={"unique": "Email already exists."},
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w\\.-]+@(gmail|yahoo|outlook)+\\.[a-z]{2,}$"
                    )
                ],
            ),
        ),
    ]
