# Generated by Django 5.2.4 on 2025-08-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0003_alter_crudmodels_options_alter_crudmodels_emailid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crudmodels",
            options={"verbose_name": "Contact"},
        ),
        migrations.AlterField(
            model_name="crudmodels",
            name="EmailId",
            field=models.EmailField(
                error_messages={"unique": "Email already exists."},
                max_length=100,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AddConstraint(
            model_name="crudmodels",
            constraint=models.UniqueConstraint(
                fields=("FirstName", "LastName"),
                name="unique_name",
                violation_error_message="A contact with this first and last name already exists.",
            ),
        ),
    ]
