# Generated by Django 5.2.4 on 2025-08-09 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0004_alter_crudmodels_options_alter_crudmodels_emailid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crudmodels",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="crudmodels",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="crudmodels",
            name="EmailId",
            field=models.EmailField(
                error_messages={"unique": "Email already exists."},
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="crudmodels",
            name="PhoneNumber",
            field=models.CharField(
                error_messages={"unique": "Phone number already exists."},
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "Enter a valid 10-digit number"
                    )
                ],
            ),
        ),
    ]
